package server

//=============================有道返回参数=======================================
type AutoGenerated struct {
	ErrorCode    string   `json:"errorCode"`    //错误返回码
	Query        string   `json:"query"`        //源语言
	Translation  []string `json:"translation"`  //翻译结果
	Basic        Basic    `json:"basic"`        //词义 基本词典
	Web          []Web    `json:"web"`          //词义 网络释义
	L            string   `json:"l"`            //源语言和目标语言
	ReturnPhrase []string `json:"returnPhrase"` //单词校验后的结果
	IsWord       bool     `json:"isWord"`       //是不是单词查询
}
type Basic struct {
	Phonetic   string   `json:"phonetic"`    //默认音标，默认是英式音标，英文查词成功，一定存在
	UkPhonetic string   `json:"uk-phonetic"` //英式音标，英文查词成功，一定存在
	UsPhonetic string   `json:"us-phonetic"` //美式音标，英文查词成功，一定存在
	Explains   []string `json:"explains"`    //基本释义
}
type Web struct {
	Key   string   `json:"key"`
	Value []string `json:"value"`
}

//==============================================================================

type FYReq struct {
	Content string `json:"content" form:"content" binding:"required"`
}
