package server

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"github.com/pkg/errors"
	"github.com/thinkeridea/go-extend/exunicode/exutf8"
	"net/http"
	"strconv"
	"time"
	"unicode/utf8"
	httpclient "youdao/util"
)

const (
	yDUrl    = "https://openapi.youdao.com/api"   //有道api地址
	signType = "v3"                               //签名版本
	uuid     = "WANGXINGZHEN"                     //用户id
	key      = "FlZf4CmGEmqTqGBHHFxjJNE7rbFvTCej" //密钥
	appKey   = "40e8d82033e12c08"                 //应用ID
	to       = "auto"                             //目标语言 auto为自动
	from     = "auto"                             //源语言 auto为自动
)

type YDRequest struct {
	CurTime  string `json:"curtime"`  //当前UTC时间戳(秒)
	SignType string `json:"signType"` //签名类型
	Sign     string `json:"sign"`     //签名
	Salt     string `json:"salt"`     //UUID
	AppKey   string `json:"appKey"`   //应用ID
	To       string `json:"to"`       //目标语言
	From     string `json:"from"`     //源语言
	Q        string `json:"q"`        //待翻译文本
}

func (r *FYReq) YouDaoServer() (res *AutoGenerated, err error) {

	res = &AutoGenerated{}
	req := YDRequest{
		CurTime:  strconv.FormatInt(time.Now().Unix(), 10),
		SignType: signType,
		Salt:     uuid,
		AppKey:   appKey,
		To:       to,
		From:     from,
		Q:        r.Content,
	}
	//生成签名
	req.buildSign()
	raw, err := json.Marshal(req)
	if err != nil {
		err = errors.WithStack(err)
		return nil, err
	}
	//切片通过json转成map
	var reqMap map[string]string
	err = json.Unmarshal(raw, &reqMap)
	if err != nil {
		err = errors.WithStack(err)
		return nil, err
	}
	//请求有道词典接口
	status, err := httpclient.PostForm(yDUrl, reqMap, nil, res)
	if err != nil {
		err = errors.WithStack(err)
		return nil, err
	}
	if status != http.StatusOK {
		err = errors.Errorf("失败，%+v", status)
		return nil, err
	}
	if res.ErrorCode != "0" {
		return nil, nil
	}
	return
}

func (S *YDRequest) buildSign() {
	//生成input
	input := S.buildInputString()
	//sign=sha256(应用ID+input+salt+curtime+应用密钥)；
	sha := sha256.Sum256([]byte(S.AppKey + input + S.Salt + S.CurTime + key))
	S.Sign = hex.EncodeToString(sha[:])
}
func (S *YDRequest) buildInputString() (input string) {
	//input的计算方式为：input=q前10个字符 + q长度 + q后10个字符（当q长度大于20）或 input=q字符串（当q长度小于等于20）
	qLength := utf8.RuneCountInString(S.Q)
	if qLength <= 20 {
		input = S.Q
		return
	}

	input = string(exutf8.RuneSub([]byte(S.Q), 0, 10)) //性能比string([]rune(S.Q)[:10])快10倍+
	input += strconv.Itoa(qLength)
	input += string(exutf8.RuneSub([]byte(S.Q), -10, 10))
	return
}
