[app.youDao]
#有道的翻译地址，不需要修改
YouDaoUrl = "https://openapi.youdao.com/api"
#应用ID
YouDaoAppID = "xxxxxxxxxxxxx"
#应用密钥
YouDaoAppKey = "xxxxxxxxxxxxxxxxxxxxxxxxxx"

[web]
#监听的地址，如果通过nginx进行转发的话，这里应设置为127.0.0.1,如果直接使用go当作web服务器的话，这里应为0.0.0.0
host = "127.0.0.1"
#监听的端口号
port = "11111"

[app.database]
#数据库地址
host = "192.168.0.170"
#端口号
port = "3306"
#用户名
username = "root"
#密码
password = "123456"
#数据库名
database_name = "test"